spring:

  # Database
  datasource:
#    url: jdbc:h2:tcp://localhost/~/userdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fullcare?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234


  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false


# OAuth2
spring.security.oauth2.client:
  registration:
    google:
      client-id: 797403577295-spn5skte9mtn11n6pu3nqnisd4eojl1h.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/login/oauth2/google
      scope:
        - profile
        - email
    naver:
      client-id: F0FHS9cOgTOnH4UfsfZ2
      client-secret: VI0YYMs2fa
      client-name: Naver
      redirect-uri: "{baseUrl}/login/oauth2/{registrationId}"
      authorization-grant-type: authorization_code
      scope:
        - name
        - email
        - profile_image
    kakao:
      client-id: 0561aec6f0dfa0b45d48e2bc97941e06
      client-secret: q2u2iqgjGq8MmE9vezAe2KCSm332EOUv
      client-name: Kakao
      client-authentication-method: client_secret_post
      redirect-uri: "{baseUrl}/login/oauth2/{registrationId}"
      authorization-grant-type: authorization_code
      scope:
        - profile_nickname
        - account_email
        - profile_image
  provider:
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: id


# JWT
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  access:
    header: Authorization
    token-validity-in-seconds: 360000

  refresh:
    header: Authorization-refresh
    token-validity-in-seconds: 86400


# Logging
logging:
  level:
    root: info

